version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data


  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  
  flower:
    build: .
    command: celery flower --broker=redis://redis:6379
    ports:
    - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6378:6379"


  bot:
    build: .
    command: python3 bot.py
    volumes:
      - .:/app
    depends_on:
      - django

volumes:
  postgres_data:
